= Testcontainers with SpringBoot and MongoDB Demo
:idprefix:
:idseparator: -
:icons: font
:imagesdir: ./images
:includes: ./_includes
:toc: preamble
:source-highlighter: coderay
:nofooter: true
//:stylesdir: src/docs/styles
:stylesheet: overrides.css
:linkcss:
:copycss: overrides.css
:rootDir: .
//For intellij Preview use following rootDir
//:rootDir: ../../..
:javaMainSourcesDir: {rootDir}/src/main/java
:javaTestSourcesDir: {rootDir}/src/test/java

This guide illustrates how to use https://www.testcontainers.org/[Testcontainers] in a SpringBoot application to test database interactions using MongoDB.

In this guide, we'll look at a sample Spring Boot application that uses Testcontainers for running unit tests with real dependencies.
The implementation uses a MongoDB database for storing data. We'll look at the necessary parts of the code that integrates Testcontainers into the app.

After the quick start, you'll have a working Spring Boot app with Testcontainers-based tests,
and will be ready to explore integrations with other databases and other technologies via Testcontainers.

== Application Entrypoint Class
[source,java]
----
include::{javaMainSourcesDir}/com/sivalabs/demo/ProductController.java[lines="10..21"]
----

== Integration Test

[source,java]
----
include::{javaTestSourcesDir}/com/sivalabs/demo/DemoApplicationTests.java[]
----

== Conclusion
Testcontainers enable using the real dependency services like SQL databases, NoSQL datastores, message brokers or any containerized services for that matter.
This approach allows you to create reliable test suites improving confidence in your code.
